### ISSUE TITLE
YOUR-TTS Paper overview

### ISSUE THREAD

**Issue by ignacio-ferreira-dev** [Vaibhavs10/ml-with-audio#10]
Hi, I think it could be nice to have a presentation about the paper YOUR-TTS: https://arxiv.org/pdf/2112.02418.pdf as it joins a lot of elements of advanced elements in TTS (Speaker embedding, Language embedding)

It would also be interesting to see how Monotonic Alignment Search and Affine Coupling Layers work both at training and at inference.
It is just an idea that I thought could be of interest. Feel free to disregard this if you don't think it should be something for a talk, that's ok.

That's all, thanks!

**Comment by Vaibhavs10** [comment]
Closing this for now. Will be back with a better way to take care of current research via this repository.
